esphome:
    name: rotex
    friendly_name: Rotex
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://Trunks1982/Daikin-Rotex-HPSU-CAN

#external_components:   # Use this block instead of the one above if you want to use the development branch
#  - source:
#      type: git
#      url: https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN.git
#      ref: dev

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: DaikinRotex Fallback Hotspot
    password: H3jGqANSa7aL

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

button:
  - platform: restart
    name: "Rotex ESP Restart"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    tx_pin: GPIO47
    rx_pin: GPIO48
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu
  canbus_id: can_bus
  update_interval: 30
  log_filter:
    name: Log Filter
  custom_request:
    name: Custom Request
  dump:
    name: Dump Senors
  entities:

# Info

    ext:
      name: Ext

#Übersicht
    water_pressure:
      name: Wasserdruck
    t_hs:
      name: T-WE
#T-WE Soll
    t_ext:  # Oder gehört hier temperature_outside rein?
      name: T-Aussen
#T-WW
#T-WW Soll
#T-Rücklauf
    flow_rate:
      name: Durchfluss
      update_interval: 10
#T-HK
#T-HK Soll
    status_kesselpumpe:
      name: Status Kesselpumpe
    runtime_compressor:
      name: Laufzeit Compressor
    runtime_pump:
      name: Laufzeit Pump
    dhw_mixer_position:
      name: DHW Mischer Position
    qboh:
      name: EHS für DHW
    ehs_for_ch:
      name: EHS fuer CH
#Energie Kühlung
    qch:
      name: Energie Heizung
    total_energy_produced:
      name: Erzeugte Energie Gesamt
    qdhw:
      name: Energie für WW
#WE Typ
#SwNr B1/U1
#SwNr Regler
#SwNr RTXRT

#Konfiguration

#Konfiguration -> Installation
#...
    outdoor_unit:
      name: Aussengerät
    indoor_unit:
      name: Innengerät
    function_ehs:
      name: Funktion EHS
    ch_support:
      name: HZ Unterstützung
#Bivalenzfunktion
    smart_grid:
      name: Smart Grid
    sg_mode:
      name: SG Modus
#HT/NT Funktion
#HT/NT Anschluss
#Raumthermostat
#Interlinkfunktion
#Konfig MFR 1
#Entlüftungsfunktion
#PWM Konfig
#...
#Sensor Konfig
#AF Anspassung
#Terminal Adresse
#Konfig System

#Konfiguration -> Anlagenkonfiguration

    power_dhw:
      name: Leistung WW
      #type: select
    power_ehs_1:
      name: Leistung EHS Stufe 1
    power_ehs_2:
      name: Leistung EHS Stufe 2
    power_biv:
      name: Leistung BIV
    tdiff_dhw_ch:
      name: TDiff-WW HZU
#Max Temp Heizung
#Bivalenztemperatur
    quiet:
      name: Flüsterbetrieb
#Sonderfunkt Schaltk
#Wartezeit Sonderfunkt
    t_dhw_1_min:
      name: Schaltschwelle TDHW
    delta_temp_ch:
      name: Spreizung HZ
    delta_temp_dhw:           # service
      name: Spreizung WW
#VerzZeitPumpe                # service
    flow_rate_min:            # service
      name: Durchfluss Min
    flow_rate_setpoint:       # serive
      name: Durchfluss Soll
    flow_rate_calc:           # service
      name: DurchflussBer
    flow_rate_hyst:           # service
      name: Durchfluss Hyst
#Anpassung T-VL Heizen
#Anpassung T-VL Kühlen
#Min Druck
#Max Druck
#Soll Druck
#Max Druckverlust
#Relaistest

# Konfiguration -> HZK Konfig
    hk_function:
      name: HK Funktion
#T-Frostschutz
#Gebäudedämumng
#Estrich
#Estrichprogramm

# Konfiguration -> HZK Konfig -> Heizen

#Heizgrenze Tag
#Heizgrenze Nacht
    heating_curve:
      name: Heizkurve
#Raumeinfluss
#RF Anpassung
    flow_temperature_day:
      name: T Vorlauf Tag
#T-Vorlauf Nacht
#Max T-Vorlauf
#Min T-Vorlauf
#Heizk Adaption

# Konfiguration -> HZK Konfig -> Kühlen

#StartKühlen A-Temp
#MaxKühlen A-Temp
#VL-SollStartKühlen
#VL-SollMaxKühlen
#MinVL-SollKühlen
#T-VLKühlen
#T_H/K Umschaltung
#KühlsollwertKorr

#Konfiguration -> WW Konfig

    circulation_with_dhw_program:
      name: Zirk mit WW-Prog
    circulation_interval_on:
        name: ZirkInterval An
    circulation_interval_off:
        name: ZirkInterval Aus
    antileg_day:
        name: AntilegTag
#AntilegZeit
    antileg_temp:
        name: AntilegTemp
    max_dhw_loading:
      name: Max WW Ladezeit
    dhw_off_time:
      name: WW Sperrzeit

# Others

    electric_heater:
      name: Heizstäbe - Für Pumpen nach Oktober 2018
    thermal_power:
      name: Thermische Leistung

# To be categorized

    bypass_valve:
      name: BPV
    circulation_pump:
      name: Umwaelzpumpe
    circulation_pump_min:
      name: Umwälzpumpe Min
    circulation_pump_max:
      name: Umwälzpumpe Max
    dhw_run:
      name: Warmwasser bereiten
    error_code:
      name: Fehlercode
    max_target_flow_temp:
      name: Max VL Soll
    min_target_flow_temp:
      name: Min VL Soll
    mode_of_operating:
      name: Betriebsart
    operating_mode:
      name: Betriebsmodus
    status_kompressor:
      name: Status Kompressor
    target_room1_temperature:
      name: Raumsoll 1
      type: select
    tdhw1:
      name: Warmwassertemperatur
    temperature_outside:
      name: Aussentemperatur
    tr:
      name: Ruecklauftemperatur Heizung
    tv:
      name: Heizkreis Vorlauf (TV)
    tvbh:
      name: Vorlauftemperatur Heizung (TVBH)
    target_hot_water_temperature:
      name: T-WW-Soll1
      type: select
    target_supply_temperature:
      name: Vorlauf Soll
